version: "3.0"

services:
  node:
    image: fampay
    build:
      context: "."
    ports:
      - "${WEB_SERVER_PORT}:5000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/usr/src/app
      - ./.node_env:/usr/src/app/.env
    links:
      - mongodb
      - worker


  worker:
    image: fampay
    command: ["npm", "run", "queue"]
    volumes:
      - ./:/usr/src/app
      - ./.node_env:/usr/src/app/.env
    links:
      - redis


  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"


  mongodb:
    image: mongo:4.2.5
    ports:
      - "${MONGO_PORT}:27017"
    command: mongod --auth
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${FAMPAY_DB}"
      FAMPAY_DB: "${FAMPAY_DB}"
      FAMPAY_ADMIN_USER: "${FAMPAY_ADMIN_USER}"
      FAMPAY_ADMIN_PASSWORD: "${FAMPAY_ADMIN_PASSWORD}"
      FAMPAY_READ_ONLY_USER: "${FAMPAY_READ_ONLY_USER}"
      FAMPAY_READ_ONLY_USER_PASSWORD: "${FAMPAY_READ_ONLY_USER_PASSWORD}"


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.

