version: "3.0"

services:
  node:
    image: fampay
    build:
      context: "."
    ports:
      - "${WEB_SERVER_PORT}:5000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/usr/src/app
      - ./.node_env:/usr/src/app/.env
    links:
      - mysql


  mysql:
    image: mysql:latest
    ports:
      - "${DB_PORT}:3306"
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - 'MYSQL_HOST=$MYSQL_HOST'
      - 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD'
      - 'MYSQL_DATABASE=$MYSQL_DATABASE'
      - 'MYSQL_USER=$MYSQL_USER'
      - 'MYSQL_PASSWORD=$MYSQL_PASSWORD'


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  mysql:
